// <auto-generated />
namespace Tee.FamilyApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DisabledEF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisabledEF));
        
        string IMigrationMetadata.Id
        {
            get { return "201606071807445_DisabledEF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
